### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by kalek2007** [EthanRStokes/Create#12]
### Describe the Bug

i have some missing textures for few items,
its missing for: water wheel, large water wheel, crushing wheel, blaze burner, etc..
![image_2023-12-01_183945399](https://github.com/Treetrain1/Create/assets/133802621/58b737ab-584c-4e83-b8d1-7e2ad1539e8a)
![image_2023-12-01_184002989](https://github.com/Treetrain1/Create/assets/133802621/f313bc00-3843-40a2-bf92-f1e1e89f274f)

### Reproduction Steps

i just open world and dont have the textures

### Expected Result

its either issue of the mod or issue of my minecraft

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by kalek2007** [comment]
i have sodium installed

**Comment by TheFattestCatProg** [comment]
install indium - fabric rendering api (helps me)

**Comment by EthanRStokes** [comment]
either needs indium or is an upstream issue.
