### ISSUE TITLE
incompatibility with the Create Deco mod

### ISSUE THREAD

**Issue by DefomCode** [EthanRStokes/Create#15]
### Describe the Bug

when installing create deco, the game crashes and writes an error where it says that create deco cannot work without create. 
That is, create deco does not see create sodium fix as a create mod

### Reproduction Steps

1. Download Create Deco 
2. Run game
3. Game Crush

### Expected Result

The game is starting

### Screenshots and Videos

![Скриншот 07-12-2023 190141](https://github.com/Treetrain1/Create/assets/91155582/45d0c847-7081-4cf8-b513-1cd21f1e89f6)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by raws** [comment]
This is the same issue as #14 (Create Deco depends on a specific build of Create, which the current release of this mod doesn't match). If you're familiar with compiling mods from source, you can apply @solonovamax's patch from that issue as a stopgap.

**Comment by solonovamax** [comment]
also, I recommend reporting the issue to create deco, as this is also an issue on their end. (they should not be depending on the build number)

**Comment by AsgerJon** [comment]
> This is the same issue as #14 (Create Deco depends on a specific build of Create, which the current release of this mod doesn't match). If you're familiar with compiling mods from source, you can apply @solonovamax's patch from that issue as a stopgap.

If you are not familiar, download the artifacts.zip file from here:
https://github.com/AsgerJon/Create-lol/actions/runs/7150968621
And use the file called:
create-sodium-fix-0.5.1-d-build.1161+mc1.20.1.jar

**Comment by raws** [comment]
We may have reached Inception levels of Create forks here 😅

**Comment by DonFlymoor** [comment]
> > This is the same issue as #14 (Create Deco depends on a specific build of Create, which the current release of this mod doesn't match). If you're familiar with compiling mods from source, you can apply @solonovamax's patch from that issue as a stopgap.
> 
> If you are not familiar, download the artifacts.zip file from here: https://github.com/AsgerJon/Create-lol/actions/runs/7150968621 And use the file called: create-sodium-fix-0.5.1-d-build.1161+mc1.20.1.jar

This should be pinned - it's super usefull

**Comment by solonovamax** [comment]
since this requires a gh account to download, I might just go and create a CI pipeline on my jenkins instance so anyone can download it

**Comment by EthanRStokes** [comment]
fixed in the latest update
