### ISSUE TITLE
won't launch

### ISSUE THREAD

**Issue by ghost** [EthanRStokes/Create#18]
### Describe the Bug

the bug is that it says even with this fork mod sodium still won't support create for 1.20.1 and also won't work with createunlimited and i have nvidia could that be an issue if it does not happen to any other systems then can you make one or do smt so it works for nvidia systems

### Reproduction Steps

1.
2.
3.
...

### Expected Result

i think that it could be what system or driver versions you have 

### Screenshots and Videos

![Skærmbillede 2023-12-30 111402](https://github.com/Treetrain1/Create/assets/127137429/7279fe5d-0d3c-4db8-8227-b1a0a55e39c6)

### Operating System

windows 11 nvidia usage

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

i use nvidium a performance mod for nvidia have to have sodium installed and starlight fabric and lithium ferrite core and dynmatic fps 

### Additional Context

it won't launch it do but won't launch the game minecraft

**Comment by Poopooracoocoo** [comment]
It looks like you've still got official Create in your mods folder as that's what's being loaded.

**Comment by EthanRStokes** [comment]
wrong repo
