### ISSUE TITLE
1.20.1 Crashing in Launcher - failure executing "entrypoint stage 'main'"

### ISSUE THREAD

**Issue by voodliedood** [EthanRStokes/Create#19]
### Describe the Bug

Honestly, I have no clue. I expected some crashes, but after fixing everything fabric's loader suggested I keep getting this error along with exit code -1:

 ```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'! 
```

### Expected Result

bingo bango - minecraft booting up as expected

### Crash Report or Log

https://pastebin.com/kPX21cQM

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods
**(EDIT: I switched to Frabric API 0.88.1 and still doesn't work)**
![image](https://github.com/Treetrain1/Create/assets/156553986/f980c29d-edc3-488a-a464-4b0fc8f478fa)
**(EDIT: I switched to Frabric API 0.88.1 and still doesn't work)**

### Additional Context

I usually only download simple client side mods, so I've never run into this. It's my first time downloading create and I picked out a fair amount of addons, so I expected some crashes, but after fixing everything fabric's loader suggested I keep getting this error

**Comment by EthanRStokes** [comment]
not a create issue.
