### ISSUE TITLE
Compatibility with iris flywheel combat

### ISSUE THREAD

**Issue by Jafooleryy** [EthanRStokes/Create#2]
### Describe the Suggestion

I use shaders and I noticed that my fps was really low when using this replacement mod, I added iris flywheel combat since with the original mod it helped boost fps. When I used it with the replacement mod you made it did not make a change, does this mod not have compatibility with create addons?

**Comment by EthanRStokes** [comment]
which version of that mod are you using?

**Comment by Hippopipo** [comment]
I am using the newest version and it does not work

**Comment by EthanRStokes** [comment]
not possible.
