### ISSUE TITLE
Create Settings are reset on every rejoin

### ISSUE THREAD

**Issue by 0PandaDEV** [EthanRStokes/Create#20]
### Describe the Bug

When i change some **Server side** settings through my client and and i save them like normal they also change in the config file on the server directly. But upon rejoining they are reset and this also happens when i restart the server the settings are reset every time but the config file says they are still changed.

### Reproduction Steps

-

### Expected Result

That the settings are consistent across restart 

### Screenshots and Videos

https://github.com/Treetrain1/Create/assets/70103896/0d2f969a-cdae-4099-859a-981b33d7450a

### Operating System

Ubuntu and Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

- accurateblockplacement 1.2.1
	- ambientsounds 5.3.5
	- amecs 1.3.10+mc.1.20.1
	- architectury 9.1.12
	- bluemap 3.20
	- borderlessmining 1.1.8+1.20.1
	- c2me 0.2.0+alpha.11.0
	   |-- c2me-base 0.2.0+alpha.11.0
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.0
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.0
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.0
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.0
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.0
	   |-- c2me-notickvd 0.2.0+alpha.11.0
	   |-- c2me-opts-allocs 0.2.0+alpha.11.0
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.0
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.0
	   |-- c2me-opts-math 0.2.0+alpha.11.0
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.0
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.0
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.0
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.0
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.0
	   |-- c2me-server-utils 0.2.0+alpha.11.0
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.0
	   |-- c2me-threading-lighting 0.2.0+alpha.11.0
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.0
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cameraoverhaul 1.4.0-fabric-universal
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- chesttracker 1.1.23
	   |-- libgui 8.0.0+1.20
	   |    |-- jankson 5.0.1+j1.2.2
	   |    \-- libninepatch 1.2.0
	   \-- whereisit 1.14.17
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- create 0.5.1-d-build.5+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10
	   |-- forgeconfigapiport 8.0.0
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_base 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    |-- porting_lib_lazy_registration 2.1.1127+1.20
	   |    \-- porting_lib_utility 2.1.1127+1.20
	   |-- porting_lib_brewing 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_client_events 2.1.1127+1.20
	   |    |-- mm 2.3
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_entity 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_mixin_extensions 2.1.1127+1.20
	   |-- porting_lib_extensions 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_fake_players 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_models 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_networking 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_obj_loader 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_tags 3.0
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_tool_actions 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_transfer 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create-track-map 1.4
	- create_structures 1.1.0
	- createaddition 0.9.0
	   \-- team_reborn_energy 2.3.0
	- createbigcannons 0.5.3.b-nightly-8a45d8e
	   \-- ritchiesprojectilelib 1.0.0-369e88d+1.20.1-fabric
	        |-- forgeconfigapiport 8.0.0
	        \-- porting_lib_networking 2.1.1127+1.20
	             |-- porting_lib_core 2.1.1127+1.20
	             \-- porting_lib_gametest 2.1.1127+1.20
	- createdieselgenerators 2.1.3
	- creategoggles 0.5.5.e
	- createoreexcavation 1.4.3
	   \-- chunk-storage-api-fabric 1.0.4
	- createutilities 0.1.3b+1.20.1
	- creativecore 2.11.15
	   \-- net_minecraftforge_eventbus 6.0.3
	- cristellib 1.1.5
	   \-- blue_endless_jankson 1.2.3
	- easiervillagertrading 1.20-fabric0.83.0-1.5.4
	   \-- gbfabrictools 1.3.5+1.20
	- essential-container 1.0.0
	   \-- essential-loader 1.2.1
	- evilcreativefly 1.2.0-1.20-fabric
	- expanded_ecosphere 3.2.4
	- extended_drawers 2.1.1+mc.1.20.1
	   |-- config_toolkit 1.0.0
	   |    |-- io_determann_shadow-api-17 0.1.1
	   |    \-- net_fabricmc_javapoet 0.1.0
	   |-- graphlib 1.4.0+1.20
	   |    |-- kmodlib-overlay 0.2.12+1.20
	   |    \-- libnetworkstack 0.10.0
	   \-- noindium 1.1.0+1.20
	- fabric-api 0.91.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.3+c81d263177
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- fabricskyboxes 0.7.3+mc1.20.1
	- fabrishot 1.10.1
	- fastipping 1.0.1
	- fastquit 3.0.0+1.20+
	- ferritecore 6.0.1
	- firstperson 2.2.4
	- fpsdisplay 3.1.0+1.20.x
	- freecam 1.2.1+1.20
	- freelook 1.1.3
	- fusion 1.1.0+c
	- geckolib 4.4
	   \-- com_eliotlash_mclib_mclib 20
	- immersive_aircraft 0.6.2+1.20.1
	- indium 1.0.27+mc1.20.1
	- inventoryhud 3.4.18
	- iris 1.6.11
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- itemphysiclite 1.6.3
	- java 17
	- keybind_fix 1.0.0
	- librarian-trade-finder 2.0.1
	- litematica 0.15.3
	- litematica_printer 3.2
	- lithium 0.11.2
	- malilib 0.16.3
	- methane 2.5.0
	- minecraft 1.20.1
	- minihud 0.27.0
	- modmenu 7.2.2
	- mousetweaks 2.25
	- mousewheelie 1.13.0+mc1.20.1
	   |-- amecsapi 1.5.1+mc1.20-pre1
	   |-- coat 1.0.0-beta.20+mc1.20-pre1
	   |-- tweed4_annotated 1.3.1+mc1.20-pre1
	   |-- tweed4_base 1.7.1+mc1.20-pre1
	   |-- tweed4_data 1.2.1+mc1.20-pre1
	   |-- tweed4_data_hjson 1.1.1+mc1.20-pre1
	   |-- tweed4_tailor_coat 1.1.3+mc1.20-pre1
	   |-- tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
	   \-- tweed4_tailor_screen 1.1.4+mc1.20-pre1
	- name_visibility 1.1
	- naturalist 4.0.3
	- no-telemetry 1.8.0
	- no_fog 1.3.5+1.16.5-1.20.4
	- nonarrator 1.0.1
	- norefreshscroll 1.0.5
	- nullscape 1.2.4
	- nvidium 0.2.5-beta
	- ping-wheel 1.7.1
	- presencefootsteps 1.9.1
	   \-- kirin 1.15.4+1.20
	- quick_hotkeys 1.0.2
	- railways 1.5.1+fabric-mc1.20.1
	   \-- mm 2.3
	- raised 3.1.1
	- reeses-sodium-options 1.6.5+mc1.20.1-build.95
	- replanter 1.3
	- roughlyenoughitems 12.0.684
	   \-- error_notifier 1.0.9
	- rrls 3.2.0-1.20.1-fabric
	- ruthenium 2.0.0
	   \-- org_json_json 20230618
	- screenshotclipboard 1.0.9
	- shulkerboxtooltip 4.0.4+1.20.1
	- sodium 0.5.3
	- sodium-extra 0.5.1+mc1.20.1-build.112
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- threadtweak 1.20.2-0.1.1
	- travelersbackpack 1.20.1-9.1.9
	- trinkets 3.7.1
	- tweakermore 3.16.0
	   |-- conditional-mixin 0.4.1
	   \-- mixinextras 0.3.2
	- viafabricplus 2.8.7
	   \-- net_lenni0451_reflect 1.2.4
	- voicechat 1.20.1-2.4.32
	- waveycapes 1.3.2
	- whoami 1.0
	- xaerominimap 23.9.3
	- xaeros-map-chest-tracker-integration 1.0.2
	- xaeroworldmap 1.37.2
	- xaerozoomout 1.1.0
	- yet_another_config_lib_v3 3.2.1+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6

### Additional Context

Its the fabric version of Create if that is not already clear and the server is self-hosted in my home network

**Comment by EthanRStokes** [comment]
i havent changed any config related code
if  you havent already, try this with the normal create fabric mod and report it there if it still happens.
if its this mod specifically, please reopen this issue
