### ISSUE TITLE
Indium 1.0.22 for Sodium 5.0 Crash

### ISSUE THREAD

**Issue by galaxygv** [EthanRStokes/Create#21]
### Describe the Bug

When Indium is installed and I click a recipe for Create mixer, game crashes. when not using indium, recipes work fine

### Reproduction Steps

1. Install Sodium 5.0
2. Install Indium 1.0.22/1.0.23
3. Lookup recipe using create mixer
4. Crash
...

### Expected Result

To work because Indium is required to not cause visual issues with Create

### Crash Report or Log

https://gist.github.com/galaxygv/9c36a02808244d5ffe4f01d29ef465fc

### Operating System

Windows 10 Enterprise LSTC

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Mods listed in crash report, too many to list

**Comment by EthanRStokes** [comment]
please use the latest versions of sodium and indium
