### ISSUE TITLE
Suggestion: make a pull request to the original create mod

### ISSUE THREAD

**Issue by Truemudkip** [EthanRStokes/Create#22]
### Describe the Suggestion

Make a PR to Create Fabric, get your mod's fixes integrated into Create Fabric if that's what you want (the modrinth project description makes it sound like that). While there still seem to be some issues the lads behind Create are probably going to end up fixing them faster than one person ever could.

**Comment by EthanRStokes** [comment]
they fixed sodium support upstream already, they are just incredibly slow to release updates.
