### ISSUE TITLE
Incompatible with Create Unlimited

### ISSUE THREAD

**Issue by Thelaststandn** [EthanRStokes/Create#24]
### Describe the Bug

When attempting to launch with the mod "Create Unlimited", the game throws a incompatibility error.

### Reproduction Steps

1. Install Create Unlimited /w Create Sodium Fix
2. Run game
3. Crash

### Expected Result

Game works without crashing.

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Create Unlimited

### Additional Context

I looked on Create Unlimiteds' github, and found this issue relating to the crash:
https://github.com/rhysdh540/create-unlimited/issues/17
In it the creator of the mod states:
"This is their fault because they use the wrong version numbers. Please make this issue there."

**Comment by EthanRStokes** [comment]
fixed in latest update

**Comment by Deemitry88** [comment]
lol it was me who made the issue on create unlimited's github
