### ISSUE TITLE
"Index -1 out of bounds for length 33" randomly when placing train tracks

### ISSUE THREAD

**Issue by SleepyBoi2852** [EthanRStokes/Create#30]
### Describe the Bug

Happens when you place a train track randomly

### Reproduction Steps

1. place a bunch of train tracks
2. eventually placing one of them will crash

### Expected Result

for it to work

### Crash Report or Log

https://mclo.gs/JPBR2Jk & https://mclo.gs/GvFpvwI

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

continuity-3.0.0-beta.4+1.20.1.jar
create-sodium-fix-0.5.1-d-build.5+mc1.20.1.jar
createaddition-fabric+1.20.1-0.9.0.jar
dynamic-fps-3.2.1+minecraft-1.20.0.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
essential_1-2-3_fabric_1-20-1.jar
ferritecore-6.0.1-fabric.jar
ImmediatelyFast-1.2.7+1.20.2.jar
immersive-portals-3.3.9-mc1.20.1-fabric.jar
indium-1.0.27+mc1.20.1.jar
lambdynamiclights-2.3.2+1.20.1.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.20.1-0.11.2.jar
mixintrace-1.1.1+1.17.jar
modmenu-7.2.2.jar
puzzle-1.5.2+1.20.jar
qfapi-7.4.0_qsl-6.1.2_fapi-0.90.0_mc-1.20.1.jar
reeses_sodium_options-1.6.5+mc1.20.1-build.95.jar
replaymod-1.20.1-2.6.14.jar
sodium-extra-0.5.1+mc1.20.1-build.112.jar
sodium-fabric-mc1.20.1-0.5.3.jar
soundphysics-fabric-1.20.1-1.2.1.jar
starlight-1.1.2+fabric.dbc156f.jar
Steam_Rails-1.5.1+fabric-mc1.20.1.jar
vivecraft-1.20.1-1.1.7-fabric.jar
worldedit-mod-7.2.15.jar

**Comment by EthanRStokes** [comment]
use create fabric.
