### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by likeusb** [EthanRStokes/Create#9]
### Describe the Bug

Basically, I've installed this mod in hopes that I can enjoy Create without having to downgrade my modslist. However, on startup, as the name implies, it crashes.
I've attached a video of this and a pastebin link to a crash report

### Reproduction Steps

1. Install mods included in the pastebin link
2. Start up minecraft

### Expected Result

No crash and actual startup

### Screenshots and Videos

https://github.com/Treetrain1/Create/assets/80967503/1b3e4de1-1c5f-407c-9147-493f3c304ba2

### Crash Report or Log

https://pastebin.com/PmKXM4zs

### Operating System

Windows 11 

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Included in pastebin link

**Comment by Poopooracoocoo** [comment]
There are a lot of mods here. Could you reduce it to  make it easier to reproduce? Or maybe make a Modrinth modpack export?

**Comment by likeusb** [comment]
Here's the Modrinth modpack:
[20.1 For Testing 1.0.0.zip](https://github.com/Treetrain1/Create/files/13344570/20.1.For.Testing.1.0.0.zip)

**Comment by likeusb** [comment]
So apparently it WAS Noxesium, disabling it seems to have fixed it. Odd, but I guess that's how it is.
So if you have the same issue:
Disable Noxesium

**Comment by Poopooracoocoo** [comment]
Noxesium's incompatibility with Porting Lib was fixed with 1.0.5 which is only for MC 1.20.2 (which Create is not available for) 

I saw https://github.com/Noxcrew/noxesium/issues/35 which was fixed by https://github.com/Noxcrew/noxesium/commit/6141ccd80bdbc26191985343e32908ec2dc92747
